### ISSUE TITLE
Support ESLint 3 and new rule format

### ISSUE THREAD

**Issue by paazmaya** [levibuzolic/eslint-plugin-no-only-tests#1]
The new rule format, introduced in the ESLint version 3, is explained here http://eslint.org/blog/2016/07/eslint-new-rule-format

Any chance of converting the rules in that format and making a new major release which support ESLint 3 and up?

**Comment by levibuzolic** [comment]
@paazmaya wow, somehow I missed this issue last year. 😓  I'll update the plugin ASAP!

**Comment by paazmaya** [comment]
Thanks! 🍇
