### ISSUE TITLE
Fixable prevents use of .only on development

### ISSUE THREAD

**Issue by Tol1** [levibuzolic/eslint-plugin-no-only-tests#25]
After release of #19 it's impossible to run only one test when developing, because I have set vscode to run `eslint --fix` on save. I don't believe this should be auto-fixable rule, as it is against first best practice on https://eslint.org/docs/developer-guide/working-with-rules#applying-fixes : it changes runtime behavior.

**Comment by levibuzolic** [comment]
Thanks for the feedback @Tol1, the auto-fix has been made configurable and disabled by default.

**Comment by Tol1** [comment]
Nice! Thanks for the quick reaction @levibuzolic
